#!/bin/bash
# Script to echo out command-line arguments
echo "The first argument is $1, the second is $2"
echo "The command itself is called $0."
echo "There are $# parameters on your cammand line"
echo "Here are all the argumments: $@" 
